import { Agent } from "./schema";

export const agents: Agent[] = [
  {
    id: "AGT-001",
    lastName: "Diomandé",
    firstName: "Moussa",
    email: "moussa.diomande@police.gouv.ci",
    matricule: "M-2024-001",
    grade: "Lieutenant",
    completion: 100,
    avatarUrl: "/homme01.png",
    gender: "Masculin",
    birthDate: "12/05/1985",
    birthPlace: "Abidjan",
    phoneNumber: "07 07 07 07 07",
  },
  {
    id: "AGT-002",
    lastName: "Kouakou",
    firstName: "Affoué",
    email: "affoue.kouakou@police.gouv.ci",
    matricule: "M-2024-002",
    grade: "Sergent-chef",
    completion: 45,
    avatarUrl: "/femme01.png",
    gender: "Féminin",
    maidenName: "Konan",
    birthDate: "23/08/1990",
    birthPlace: "Bouaké",
    phoneNumber: "01 02 03 04 05",
  },
  {
    id: "AGT-003",
    lastName: "Touré",
    firstName: "Seydou",
    email: "seydou.toure@police.gouv.ci",
    matricule: "M-2024-003",
    grade: "Capitaine",
    completion: 100,
    avatarUrl: "/homme02.png",
    gender: "Masculin",
    birthDate: "15/01/1982",
    birthPlace: "Korhogo",
    phoneNumber: "05 05 05 05 05",
  },
  {
    id: "AGT-004",
    lastName: "Bamba",
    firstName: "Saran",
    email: "saran.bamba@police.gouv.ci",
    matricule: "M-2024-004",
    grade: "Commissaire",
    completion: 10,
    avatarUrl: "/femme02.png",
    gender: "Féminin",
    birthDate: "30/11/1978",
    birthPlace: "Man",
    phoneNumber: "07 48 55 21 36",
  },
  {
    id: "AGT-005",
    lastName: "Kouamé",
    firstName: "Kouadio",
    email: "kouadio.kouame@police.gouv.ci",
    matricule: "M-2024-005",
    grade: "Sous-officier",
    completion: 85,
    avatarUrl: "/homme03.png",
    gender: "Masculin",
    birthDate: "05/04/1995",
    birthPlace: "Yamoussoukro",
    phoneNumber: "01 42 58 96 32",
  },
];
