import { Agent } from "./schema";

export const agents: Agent[] = [
  {
    id: "AGT-001",
    lastName: "Dupont",
    firstName: "Jean",
    email: "jean.dupont@police.gouv.ci",
    matricule: "M-2024-001",
    grade: "Lieutenant",
    completion: 100,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jean",
    gender: "Masculin",
    birthDate: "12/05/1985",
    birthPlace: "Abidjan",
    phoneNumber: "07 07 07 07 07",
  },
  {
    id: "AGT-002",
    lastName: "Kouassi",
    firstName: "Marie",
    email: "marie.kouassi@police.gouv.ci",
    matricule: "M-2024-002",
    grade: "Sergent-chef",
    completion: 45,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marie",
    gender: "Féminin",
    maidenName: "Konan",
    birthDate: "23/08/1990",
    birthPlace: "Bouaké",
    phoneNumber: "01 02 03 04 05",
  },
  {
    id: "AGT-003",
    lastName: "Traoré",
    firstName: "Ibrahim",
    email: "ibrahim.traore@police.gouv.ci",
    matricule: "M-2024-003",
    grade: "Capitaine",
    completion: 100,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ibrahim",
    gender: "Masculin",
    birthDate: "15/01/1982",
    birthPlace: "Korhogo",
    phoneNumber: "05 05 05 05 05",
  },
  {
    id: "AGT-004",
    lastName: "Koné",
    firstName: "Awa",
    email: "awa.kone@police.gouv.ci",
    matricule: "M-2024-004",
    grade: "Commissaire",
    completion: 10,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Awa",
    gender: "Féminin",
    birthDate: "30/11/1978",
    birthPlace: "Man",
    phoneNumber: "07 48 55 21 36",
  },
  {
    id: "AGT-005",
    lastName: "Yao",
    firstName: "Koffi",
    email: "koffi.yao@police.gouv.ci",
    matricule: "M-2024-005",
    grade: "Sous-officier",
    completion: 85,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Koffi",
    gender: "Masculin",
    birthDate: "05/04/1995",
    birthPlace: "Yamoussoukro",
    phoneNumber: "01 42 58 96 32",
  },
];
