import { Mail } from "../schema";
export type { Mail };

export const mails: Mail[] = [
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    reference: "ARR-2026-02-23-0012",
    receivedAt: new Date("2026-02-23T10:30:00"),
    emittedAt: new Date("2026-02-21T08:15:00"),
    sender: "Ministère de l'Intérieur et de la Sécurité",
    senderType: "ADMINISTRATION",
    officialName: "Ministère de l'Intérieur et de la Sécurité",
    identificationNumber: "GOV-CIV-1001",
    phone: "+225 01 23 45 67 89",
    email: "contact@interieur.gouv.ci",
    senderOrganization: "Cabinet du Ministre",
    recipientService: "Direction Générale de la Police Nationale",
    object:
      "Convocation à la réunion interministérielle extraordinaire concernant le renforcement du dispositif de sécurité nationale pour la période électorale de 2026 et l'évaluation des menaces aux frontières terrestres et maritimes du pays.",
    type: "COURRIER_ARRIVEE",
    priority: "URGENT",
    confidentiality: "CONFIDENTIEL",
    status: "EN_TRAITEMENT",
    pageCount: 2,
    registeredBy: "Agent Koné",
    scanUrl: "/Courrier.pdf",
    read: true,
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    reference: "INT-2026-02-20-0045",
    receivedAt: new Date("2026-02-20T14:15:00"),
    emittedAt: new Date("2026-02-19T10:00:00"),
    sender: "Direction des Ressources Humaines",
    senderType: "ADMINISTRATION",
    officialName: "Direction des Ressources Humaines",
    identificationNumber: "GOV-CIV-2045",
    phone: "+225 05 55 55 55 55",
    email: "drh@dgpn.gouv.ci",
    senderOrganization: "DRH - DGPN",
    recipientService: "Tous les Commissariats",
    object:
      "Note de service à l'attention de tous les chefs d'unités portant sur les nouvelles directives de déploiement des effectifs de sécurité dans les zones à forte densité de population dans le District Autonome d'Abidjan et à l'intérieur du pays, avec effet immédiat.",
    type: "NOTE_INTERNE",
    priority: "URGENT",
    confidentiality: "NORMAL",
    status: "TRANSMIS",
    pageCount: 1,
    registeredBy: "Agent Sylla",
    read: true,
  },
  {
    id: "3b241101-e2bb-11d4-a716-446655440000",
    reference: "DEP-2026-02-18-0003",
    receivedAt: new Date("2026-02-18T09:00:00"),
    emittedAt: new Date("2026-02-17T16:30:00"),
    sender: "Commissariat de Police du 1er Arrondissement Plateau",
    senderType: "ADMINISTRATION",
    officialName: "Préfecture de Police d'Abidjan - 1er Arrondissement",
    identificationNumber: "GOV-CIV-8012",
    phone: "+225 01 02 03 04 05",
    email: "commissariat.plateau@interieur.gouv.ci",
    senderOrganization: "Police Nationale",
    recipientService: "Préfecture d'Abidjan",
    object:
      "Transmission du rapport exhaustif d'activité hebdomadaire couvrant les interventions de maintien de l'ordre, les opérations de fluidité routière, et la lutte contre la grande criminalité dans la commune du Plateau pour la période du 10 au 16 Février 2026.",
    type: "COURRIER_DEPART",
    priority: "NORMAL",
    confidentiality: "NORMAL",
    status: "ARCHIVE",
    pageCount: 15,
    registeredBy: "Agent Bamba",
    scanUrl: "/Courrier.pdf",
    read: true,
  },
  {
    id: "3b241101-e2bb-11d4-a716-446655440001",
    reference: "ARR-2026-02-22-0015",
    receivedAt: new Date("2026-02-22T16:45:00"),
    emittedAt: new Date("2026-02-20T11:20:00"),
    sender: "Mairie de Cocody",
    senderType: "ADMINISTRATION",
    officialName: "Mairie de Cocody",
    identificationNumber: "GOV-CIV-3022",
    phone: "+225 27 22 44 12 34",
    email: "contact@mairie-cocody.ci",
    senderOrganization: "Service Technique",
    recipientService: "Direction Logistique - DGPN",
    object:
      "Demande formelle d'assistance et de détachement d'éléments de la Brigade de la Circulation pour encadrer les travaux de réfection lourde prévus sur le Boulevard Mitterrand et éviter les congestions majeures prévues aux heures de pointe durant les trois prochains mois.",
    type: "COURRIER_ARRIVEE",
    priority: "NORMAL",
    confidentiality: "NORMAL",
    status: "ENREGISTRE",
    pageCount: 3,
    registeredBy: "Agent Koné",
    read: false,
  },
];
